### ISSUE TITLE
'module' object has no attribute 'quote_plus' when adding a location

### ISSUE THREAD

**Issue by Luis-Palacios** [mishbahr/djangocms-gmaps#1]
Hey there, i am trying this plugin, i am able to add the plugin but when i add a location it crash and says ''module' object has no attribute 'quote_plus' when adding a location'

I am using django 1.7.5 and django-cms 3.0.12

**Comment by mishbahr** [comment]
Hi, 

Thanks for taking the time to report this bug. 
I'll need some time to investigate this issue and I'll try to push a fix as soon as possible. 
In the mean time, could you please let me know the version of python you are using. 

Many Thanks

**Comment by mishbahr** [comment]
Try this! Install directly from github.. Let me know if this fixes your issue. I'll push it PyPi after confirmation from you

**Comment by Luis-Palacios** [comment]
looks like it has to do with my python version(3.4) i was doing some debbuging and acordin to [this](https://docs.python.org/2/library/urllib.html) 

> The urllib module has been split into parts and renamed in Python 3 to urllib.request, urllib.parse, and urllib.error. The 2to3 tool will automatically adapt imports when converting your sources to Python 3. Also note that the urllib.request.urlopen() function in Python 3 is equivalent to urllib2.urlopen() and that urllib.urlopen() has been removed.

so if i change the line 172 in models.py from this: 'address': urllib.quote_plus(self.address) to this 'address': urllib.parse.quote_plus(self.address) it works just fine.

just added .parse after urlib

**Comment by mishbahr** [comment]
Yep. I've fixed that now. Please try the github version.

**Comment by Luis-Palacios** [comment]
I am getting TemplateDoesNotExist at //
djangocms_gmaps/infowindow.html when installing from github

**Comment by mishbahr** [comment]
Hmm... not sure why you getting that error. I've pushed the latest change to pypi. Please install the latest version .. the issue should be fixed.

**Comment by Luis-Palacios** [comment]
i am still getting the TemplateDoesNotExist error do i have to do something else to uninstall the package? because all i did was pip uninstall, and i had already ran the migrations the firstime

**Comment by Luis-Palacios** [comment]
Ok its working, i had to restar server. Sorry about that, and thank you for your quick response
